Vagrant.configure(2) do |config|
  config.vm.box = 'ubuntu/xenial64'

  config.vm.provision "shell", inline: <<-EOS
    apt-get install -y python
  EOS

  config.vm.provision :ansible do |ansible|
    ansible.playbook = 'playbook.yml'
  end

end
